// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPackageManagementSystem.Repository.Data;

#nullable disable

namespace TravelPackageManagementSystem.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117153720_AddGalleryToContext")]
    partial class AddGalleryToContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TravelPackagePackageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("TravelPackagePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<int>("HolidayCount")
                        .HasColumnType("int");

                    b.Property<int>("HotelCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            HolidayCount = 29,
                            HotelCount = 18,
                            ImageUrl = "/lib/Image/meghalaya.jpg",
                            StateName = "Meghalaya"
                        },
                        new
                        {
                            DestinationId = 2,
                            HolidayCount = 48,
                            HotelCount = 30,
                            ImageUrl = "/lib/Image/Tamilnadu.jpg",
                            StateName = "Tamil Nadu"
                        },
                        new
                        {
                            DestinationId = 3,
                            HolidayCount = 36,
                            HotelCount = 22,
                            ImageUrl = "/lib/Image/Kerala.jpg",
                            StateName = "Kerala"
                        },
                        new
                        {
                            DestinationId = 4,
                            HolidayCount = 40,
                            HotelCount = 25,
                            ImageUrl = "/lib/Image/goa.jpg",
                            StateName = "Goa"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Krang Suri Falls",
                            DestinationId = 1,
                            ImageUrl = "/lib/Image/meg1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Root Bridges",
                            DestinationId = 1,
                            ImageUrl = "/lib/Image/meg2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Dawki River",
                            DestinationId = 1,
                            ImageUrl = "/lib/Image/meg3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Meenakshi Temple",
                            DestinationId = 2,
                            ImageUrl = "/lib/Image/Tamil1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Munnar Hills",
                            DestinationId = 3,
                            ImageUrl = "/lib/Image/Kerala1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Baga Beach",
                            DestinationId = 4,
                            ImageUrl = "/lib/Image/Goa1.jpg"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Itinerary", b =>
                {
                    b.Property<int>("ItineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryId"));

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("ItineraryId");

                    b.HasIndex("PackageId");

                    b.ToTable("Itineraries");

                    b.HasData(
                        new
                        {
                            ItineraryId = 1,
                            ActivityDescription = "Pick up from Guwahati...",
                            ActivityTitle = "Arrival in Shillong",
                            DayNumber = 1,
                            Exclusions = "Airfare;Lunch;Personal Expenses",
                            Inclusions = "Resort Stay;Daily Breakfast;Private SUV",
                            PackageId = 3
                        },
                        new
                        {
                            ItineraryId = 2,
                            ActivityDescription = "Breathtaking views...",
                            ActivityTitle = "Laitlum Canyons",
                            DayNumber = 2,
                            Exclusions = "Airfare;Lunch;Personal Expenses",
                            Inclusions = "Resort Stay;Daily Breakfast;Private SUV",
                            PackageId = 3
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.TravelPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PackageId");

                    b.HasIndex("DestinationId");

                    b.ToTable("TravelPackages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            DestinationId = 1,
                            Duration = "3 Days",
                            ImageUrl = "/lib/Image/meghalaya.jpg",
                            IsTrending = false,
                            Location = "Shillong Peak",
                            PackageName = "Quick Escape",
                            Price = 9999.00m,
                            Status = 0
                        },
                        new
                        {
                            PackageId = 2,
                            DestinationId = 1,
                            Duration = "5 Days",
                            ImageUrl = "/lib/Image/Waterfall.jpg",
                            IsTrending = true,
                            Location = "Root Bridges",
                            PackageName = "The Classic",
                            Price = 17999.00m,
                            Status = 0
                        },
                        new
                        {
                            PackageId = 3,
                            DestinationId = 1,
                            Duration = "7 Days",
                            ImageUrl = "/lib/Image/meghbg.jpg",
                            IsTrending = false,
                            Location = "Hidden Caves",
                            PackageName = "Deep Explorer",
                            Price = 25999.00m,
                            Status = 0
                        },
                        new
                        {
                            PackageId = 4,
                            DestinationId = 2,
                            Duration = "48 Days",
                            ImageUrl = "/lib/Image/Tamilnadu.jpg",
                            IsTrending = false,
                            PackageName = "Temple Trail",
                            Price = 18500.00m,
                            Status = 0
                        },
                        new
                        {
                            PackageId = 5,
                            DestinationId = 3,
                            Duration = "36 Days",
                            ImageUrl = "/lib/Image/Kerala.jpg",
                            IsTrending = false,
                            PackageName = "Backwater Bliss",
                            Price = 22000.00m,
                            Status = 0
                        },
                        new
                        {
                            PackageId = 6,
                            DestinationId = 4,
                            Duration = "40 Days",
                            ImageUrl = "/lib/Image/goa.jpg",
                            IsTrending = false,
                            PackageName = "Sun & Sand",
                            Price = 15000.00m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "test@example.com",
                            Password = "HashedPassword123",
                            Role = 2,
                            Username = "Traveler01"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Booking", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.TravelPackage", "TravelPackage")
                        .WithMany()
                        .HasForeignKey("TravelPackagePackageId");

                    b.HasOne("TravelPackageManagementSystem.Repository.Models.User", null)
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPackage");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.GalleryImage", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Destination", "ParentDestination")
                        .WithMany("GalleryImages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDestination");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Itinerary", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.TravelPackage", "TravelPackage")
                        .WithMany("Itineraries")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPackage");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Payment", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.TravelPackage", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Destination", "ParentDestination")
                        .WithMany("TravelPackages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDestination");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Destination", b =>
                {
                    b.Navigation("GalleryImages");

                    b.Navigation("TravelPackages");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.TravelPackage", b =>
                {
                    b.Navigation("Itineraries");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
