// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPackageManagementSystem.Repository.Data;

#nullable disable

namespace TravelPackageManagementSystem.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128052039_InitialCreateV6")]
    partial class InitialCreateV6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<int>("HolidayCount")
                        .HasColumnType("int");

                    b.Property<int>("HotelCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            HolidayCount = 29,
                            HotelCount = 18,
                            ImageUrl = "/lib/Image/meghalaya.jpg",
                            StateName = "Meghalaya"
                        },
                        new
                        {
                            DestinationId = 2,
                            HolidayCount = 48,
                            HotelCount = 30,
                            ImageUrl = "/lib/Image/Tamilnadu.jpg",
                            StateName = "Tamil Nadu"
                        },
                        new
                        {
                            DestinationId = 3,
                            HolidayCount = 36,
                            HotelCount = 22,
                            ImageUrl = "/lib/Image/Kerala.jpg",
                            StateName = "Kerala"
                        },
                        new
                        {
                            DestinationId = 4,
                            HolidayCount = 40,
                            HotelCount = 25,
                            ImageUrl = "/lib/Image/goa.jpg",
                            StateName = "Goa"
                        },
                        new
                        {
                            DestinationId = 5,
                            HolidayCount = 60,
                            HotelCount = 45,
                            ImageUrl = "/lib/TrendingImage/Mumbai.jpg",
                            StateName = "Maharashtra"
                        },
                        new
                        {
                            DestinationId = 6,
                            HolidayCount = 75,
                            HotelCount = 50,
                            ImageUrl = "/lib/TrendingImage/Hawa Mahal Jaipur.jpg",
                            StateName = "Rajasthan"
                        },
                        new
                        {
                            DestinationId = 7,
                            HolidayCount = 30,
                            HotelCount = 20,
                            ImageUrl = "/lib/TrendingImage/Darjiling.jpg",
                            StateName = "West Bengal"
                        },
                        new
                        {
                            DestinationId = 8,
                            HolidayCount = 25,
                            HotelCount = 15,
                            ImageUrl = "/lib/TrendingImage/Gangtok.jpg",
                            StateName = "Sikkim"
                        },
                        new
                        {
                            DestinationId = 9,
                            HolidayCount = 55,
                            HotelCount = 40,
                            ImageUrl = "/lib/TrendingImage/Banaras.jpg",
                            StateName = "Uttar Pradesh"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Krang Suri Falls",
                            DestinationId = 1,
                            ImageUrl = "/lib/Image/meg1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Root Bridges",
                            DestinationId = 1,
                            ImageUrl = "/lib/Image/meg2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Dawki River",
                            DestinationId = 1,
                            ImageUrl = "/lib/Image/meg3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Meenakshi Temple",
                            DestinationId = 2,
                            ImageUrl = "/lib/Image/t2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Munnar Hills",
                            DestinationId = 3,
                            ImageUrl = "/lib/Image/k1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Baga Beach",
                            DestinationId = 4,
                            ImageUrl = "/lib/Image/goa3.jpg"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.HostContactDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostAgencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HostContactDetails");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Itinerary", b =>
                {
                    b.Property<int>("ItineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryId"));

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("ItineraryId");

                    b.HasIndex("PackageId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingId1");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.TravelPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HostId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("HostId");

                    b.ToTable("TravelPackages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Meghalaya",
                            DestinationId = 1,
                            Duration = "3 Days",
                            ImageUrl = "/lib/Image/meghalaya.jpg",
                            IsTrending = false,
                            Location = "Shillong Peak",
                            PackageName = "Quick Escape",
                            PackageType = "",
                            Price = 9999.00m,
                            ThumbnailUrl1 = "/lib/Image/meg4.jpg",
                            ThumbnailUrl2 = "/lib/Image/meghbg.jpg",
                            ThumbnailUrl3 = "/lib/Image/meg3.jpg"
                        },
                        new
                        {
                            PackageId = 2,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Tamil Nadu",
                            DestinationId = 2,
                            Duration = "8 Days",
                            ImageUrl = "/lib/Image/Tamilnadu.jpg",
                            IsTrending = false,
                            Location = "Madurai",
                            PackageName = "Temple Trail",
                            PackageType = "",
                            Price = 18500.00m,
                            ThumbnailUrl1 = "/lib/Image/t4.jpg",
                            ThumbnailUrl2 = "/lib/Image/t25.jpg",
                            ThumbnailUrl3 = "/lib/Image/t3.jpg"
                        },
                        new
                        {
                            PackageId = 3,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Kerala",
                            DestinationId = 3,
                            Duration = "6 Days",
                            ImageUrl = "/lib/Image/Kerala.jpg",
                            IsTrending = false,
                            Location = "Alleppey",
                            PackageName = "Backwater Bliss",
                            PackageType = "",
                            Price = 22000.00m,
                            ThumbnailUrl1 = "/lib/Image/k32.jpg",
                            ThumbnailUrl2 = "/lib/Image/k35.jpg",
                            ThumbnailUrl3 = "/lib/Image/k3.jpg"
                        },
                        new
                        {
                            PackageId = 4,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Description = "A bustling metropolis blending colonial heritage and Bollywood glamour.",
                            Destination = "Maharashtra",
                            DestinationId = 5,
                            Duration = "5 Days",
                            ImageUrl = "/lib/TrendingImage/Mumbai.jpg",
                            IsTrending = true,
                            Location = "Gateway of India",
                            PackageName = "Mumbai Heritage",
                            PackageType = "",
                            Price = 35000.00m,
                            ThumbnailUrl1 = "/lib/Image/mumbai1.jpg",
                            ThumbnailUrl2 = "/lib/Image/mumbai2.jpg",
                            ThumbnailUrl3 = "/lib/Image/mumbai3.jpg"
                        },
                        new
                        {
                            PackageId = 5,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Rajasthan",
                            DestinationId = 6,
                            Duration = "6 Days",
                            ImageUrl = "/lib/TrendingImage/Hawa Mahal Jaipur.jpg",
                            IsTrending = true,
                            Location = "Jaipur",
                            PackageName = "Pink City Tour",
                            PackageType = "",
                            Price = 65000.00m,
                            ThumbnailUrl1 = "/lib/Image/jaipur1.jpg",
                            ThumbnailUrl2 = "/lib/Image/jaipur2.jpg",
                            ThumbnailUrl3 = "/lib/Image/jaipur3.jpg"
                        },
                        new
                        {
                            PackageId = 6,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Sikkim",
                            DestinationId = 8,
                            Duration = "8 Days",
                            ImageUrl = "/lib/TrendingImage/Gangtok.jpg",
                            IsTrending = true,
                            Location = "Gangtok",
                            PackageName = "Sikkim Adventure",
                            PackageType = "",
                            Price = 70000.00m,
                            ThumbnailUrl1 = "/lib/Image/gangtok1.jpg",
                            ThumbnailUrl2 = "/lib/Image/gangtok2.jpg",
                            ThumbnailUrl3 = "/lib/Image/gangtok3.jpg"
                        },
                        new
                        {
                            PackageId = 7,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "West Bengal",
                            DestinationId = 7,
                            Duration = "4 Days",
                            ImageUrl = "/lib/TrendingImage/Darjiling.jpg",
                            IsTrending = true,
                            Location = "Darjeeling",
                            PackageName = "Darjeeling Tea",
                            PackageType = "",
                            Price = 5500.00m,
                            ThumbnailUrl1 = "/lib/Image/darjiling1.jpg",
                            ThumbnailUrl2 = "/lib/Image/darjiling2.jpg",
                            ThumbnailUrl3 = "/lib/Image/darjiling3.jpg"
                        },
                        new
                        {
                            PackageId = 8,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Uttar Pradesh",
                            DestinationId = 9,
                            Duration = "3 Days",
                            ImageUrl = "/lib/TrendingImage/Banaras.jpg",
                            IsTrending = true,
                            Location = "Varanasi",
                            PackageName = "Varanasi Spiritual",
                            PackageType = "",
                            Price = 83000.00m,
                            ThumbnailUrl1 = "/lib/Image/banaras1.jpg",
                            ThumbnailUrl2 = "/lib/Image/banaras2.jpg",
                            ThumbnailUrl3 = "/lib/Image/banaras3.jpg"
                        },
                        new
                        {
                            PackageId = 9,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Kerala",
                            DestinationId = 3,
                            Duration = "5 Days",
                            ImageUrl = "/lib/TrendingImage/Munnar.jpg",
                            IsTrending = true,
                            Location = "Munnar",
                            PackageName = "Misty Munnar",
                            PackageType = "",
                            Price = 50000.00m,
                            ThumbnailUrl1 = " /lib/Image/munnar1.jpg",
                            ThumbnailUrl2 = "/lib/Image/munnar2.jpg",
                            ThumbnailUrl3 = "/lib/Image/munnar4.jpg"
                        },
                        new
                        {
                            PackageId = 10,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Goa",
                            DestinationId = 4,
                            Duration = "3 Days",
                            ImageUrl = "/lib/TrendingImage/Goa.jpg",
                            IsTrending = true,
                            Location = "Calangute",
                            PackageName = "Goa Sundowner",
                            PackageType = "",
                            Price = 12500.00m,
                            ThumbnailUrl1 = " /lib/Image/goa1.jpg",
                            ThumbnailUrl2 = "/lib/Image/goa2.jpg",
                            ThumbnailUrl3 = "/lib/Image/goa3.jpg"
                        },
                        new
                        {
                            PackageId = 11,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Tamil Nadu",
                            DestinationId = 2,
                            Duration = "5 Days",
                            ImageUrl = "/lib/TrendingImage/Ooty.jpg",
                            IsTrending = true,
                            Location = "Ooty",
                            PackageName = "Ooty Gardens",
                            PackageType = "",
                            Price = 52000.00m,
                            ThumbnailUrl1 = "/lib/Image/ooty.jpg",
                            ThumbnailUrl2 = "/lib/Image/ooty2.jpg",
                            ThumbnailUrl3 = "/lib/Image/ooty3.jpg"
                        },
                        new
                        {
                            PackageId = 12,
                            ApprovalStatus = 1,
                            AvailabilityStatus = 0,
                            Destination = "Uttar Pradesh",
                            DestinationId = 9,
                            Duration = "3 Days",
                            ImageUrl = "/lib/TrendingImage/Vrindavan.jpg",
                            IsTrending = true,
                            Location = "Vrindavan",
                            PackageName = "Sacred Vrindavan",
                            PackageType = "",
                            Price = 67000.00m,
                            ThumbnailUrl1 = "/lib/Image/vrindavan5.jpg",
                            ThumbnailUrl2 = "/lib/Image/vrindavan3.jpg",
                            ThumbnailUrl3 = "/lib/Image/vrindavan2.jpg"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@travel.com",
                            Password = "HashedPassword",
                            Role = 2,
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Booking", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.TravelPackage", "TravelPackage")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelPackageManagementSystem.Repository.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.GalleryImage", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Destination", "ParentDestination")
                        .WithMany("GalleryImages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDestination");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Itinerary", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.TravelPackage", "TravelPackage")
                        .WithMany("Itineraries")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPackage");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Payment", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Booking", null)
                        .WithMany("Payments")
                        .HasForeignKey("BookingId1");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.TravelPackage", b =>
                {
                    b.HasOne("TravelPackageManagementSystem.Repository.Models.Destination", "ParentDestination")
                        .WithMany("TravelPackages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelPackageManagementSystem.Repository.Models.HostContactDetail", "Host")
                        .WithMany("TravelPackages")
                        .HasForeignKey("HostId");

                    b.Navigation("Host");

                    b.Navigation("ParentDestination");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.Destination", b =>
                {
                    b.Navigation("GalleryImages");

                    b.Navigation("TravelPackages");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.HostContactDetail", b =>
                {
                    b.Navigation("TravelPackages");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.TravelPackage", b =>
                {
                    b.Navigation("Itineraries");
                });

            modelBuilder.Entity("TravelPackageManagementSystem.Repository.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
